---
# spa-run:
#   schema: 1
#   summary: Add a Splunk license to the license manager.
#   description: Installs the configured license file on the license manager host.
#   category: operations
#   risk: mutating
#   examples:
#     - spa run splunk_license
# add a splunk license if not existing

- name: Add splunk license to license manager
  hosts: role_license_manager
  become: true
  become_user: root

  tasks:
    - name: Call license from role license_manager
      ansible.builtin.include_role:
        name: license_manager
        tasks_from: license
